use bd_sigdes_cj;
############################################################################
#################INGRESO DE DATOS PREDETERMINADOS A LA BD ##################

######################################## NACIONALIDADES ####################################
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Afganistán','AFGANA','AFG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Albania','ALBANESA','ALB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Alemania','ALEMANA','DEU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Andorra','ANDORRANA','AND');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Angola','ANGOLEÑA','AGO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('AntiguayBarbuda','ANTIGUANA','ATG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('ArabiaSaudita','SAUDÍ','SAU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Argelia','ARGELINA','DZA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Argentina','ARGENTINA','ARG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Armenia','ARMENIA','ARM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Aruba','ARUBEÑA','ABW');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Australia','AUSTRALIANA','AUS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Austria','AUSTRIACA','AUT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Azerbaiyán','AZERBAIYANA','AZE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bahamas','BAHAMEÑA','BHS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bangladés','BANGLADESÍ','BGD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Barbados','BARBADENSE','BRB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Baréin','BAREINÍ','BHR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bélgica','BELGA','BEL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Belice','BELICEÑA','BLZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Benín','BENINÉSA','BEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bielorrusia','BIELORRUSA','BLR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Birmania','BIRMANA','MMR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bolivia','BOLIVIANA','BOL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('BosniayHerzegovina','BOSNIA','BIH');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Botsuana','BOTSUANA','BWA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Brasil','BRASILEÑA','BRA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Brunéi','BRUNEANA','BRN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bulgaria','BÚLGARA','BGR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('BurkinaFaso','BURKINÉS','BFA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Burundi','BURUNDÉSA','BDI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Bután','BUTANÉSA','BTN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CaboVerde','CABOVERDIANA','CPV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Camboya','CAMBOYANA','KHM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Camerún','CAMERUNESA','CMR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Canadá','CANADIENSE','CAN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Catar','CATARÍ','QAT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Chad','CHADIANA','TCD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Chile','CHILENA','CHL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('China','CHINA','CHN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Chipre','CHIPRIOTA','CYP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CiudaddelVaticano','VATICANA','VAT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Colombia','COLOMBIANA','COL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Comoras','COMORENSE','COM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CoreadelNorte','NORCOREANA','PRK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CoreadelSur','SURCOREANA','KOR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CostadeMarfil','MARFILEÑA','CIV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('CostaRica','COSTARRICENSE','CRI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Croacia','CROATA','HRV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Cuba','CUBANA','CUB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Dinamarca','DANÉSA','DNK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Dominica','DOMINIQUÉS','DMA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ecuador','ECUATORIANA','ECU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Egipto','EGIPCIA','EGY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('ElSalvador','SALVADOREÑA','SLV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('EmiratosÁrabesUnidos','EMIRATÍ','ARE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eritrea','ERITREA','ERI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eslovaquia','ESLOVACA','SVK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eslovenia','ESLOVENA','SVN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('España','ESPAÑOLA','ESP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('EstadosUnidos','ESTADOUNIDENSE','USA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Estonia','ESTONIA','EST');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Etiopía','ETÍOPE','ETH');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Filipinas','FILIPINA','PHL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Finlandia','FINLANDÉSA','FIN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Fiyi','FIYIANA','FJI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Francia','FRANCÉSA','FRA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gabón','GABONÉSA','GAB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gambia','GAMBIANA','GMB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Georgia','GEORGIANA','GEO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gibraltar','GIBRALTAREÑA','GIB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ghana','GHANÉSA','GHA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Granada','GRANADINA','GRD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Grecia','GRIEGA','GRC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Groenlandia','GROENLANDÉSA','GRL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guatemala','GUATEMALTECA','GTM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guineaecuatorial','ECUATOGUINEANA','GNQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guinea','GUINEANA','GIN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guinea-Bisáu','GUINEANA','GNB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guyana','GUYANESA','GUY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Haití','HAITIANA','HTI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Honduras','HONDUREÑA','HND');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Hungría','HÚNGARA','HUN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('India','HINDÚ','IND');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Indonesia','INDONESIA','IDN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irak','IRAQUÍ','IRQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irán','IRANÍ','IRN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irlanda','IRLANDÉSA','IRL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Islandia','ISLANDÉSA','ISL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasCook','COOKIANA','COK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasMarshall','MARSHALÉSA','MHL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasSalomón','SALOMONENSE','SLB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Israel','ISRAELÍ','ISR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Italia','ITALIANA','ITA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Jamaica','JAMAIQUINA','JAM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Japón','JAPONÉSA','JPN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Jordania','JORDANA','JOR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kazajistán','KAZAJA','KAZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kenia','KENIATA','KEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kirguistán','KIRGUISA','KGZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kiribati','KIRIBATIANA','KIR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kuwait','KUWAITÍ','KWT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Laos','LAOSIANA','LAO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Lesoto','LESOTENSE','LSO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Letonia','LETÓNA','LVA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Líbano','LIBANÉSA','LBN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Liberia','LIBERIANA','LBR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Libia','LIBIA','LBY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Liechtenstein','LIECHTENSTEINIANA','LIE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Lituania','LITUANA','LTU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Luxemburgo','LUXEMBURGUÉSA','LUX');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Madagascar','MALGACHE','MDG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malasia','MALASIA','MYS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malaui','MALAUÍ','MWI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Maldivas','MALDIVA','MDV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malí','MALIENSE','MLI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malta','MALTÉSA','MLT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Marruecos','MARROQUÍ','MAR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Martinica','MARTINIQUÉS','MTQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mauricio','MAURICIANA','MUS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mauritania','MAURITANA','MRT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('México','MEXICANA','MEX');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Micronesia','MICRONESIA','FSM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Moldavia','MOLDAVA','MDA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mónaco','MONEGASCA','MCO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mongolia','MONGOLA','MNG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Montenegro','MONTENEGRINA','MNE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mozambique','MOZAMBIQUEÑA','MOZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Namibia','NAMIBIA','NAM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nauru','NAURUANA','NRU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nepal','NEPALÍ','NPL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nicaragua','NICARAGÜENSE','NIC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Níger','NIGERINA','NER');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nigeria','NIGERIANA','NGA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Noruega','NORUEGA','NOR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('NuevaZelanda','NEOZELANDÉSA','NZL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Omán','OMANÍ','OMN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PaísesBajos','NEERLANDÉSA','NLD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Pakistán','PAKISTANÍ','PAK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Palaos','PALAUANA','PLW');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Palestina','PALESTINA','PSE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Panamá','PANAMEÑA','PAN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PapúaNuevaGuinea','PAPÚ','PNG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Paraguay','PARAGUAYA','PRY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Perú','PERUANA','PER');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Polonia','POLACA','POL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Portugal','PORTUGUÉSA','PRT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PuertoRico','PUERTORRIQUEÑA','PRI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('ReinoUnido','BRITÁNICA','GBR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaCentroafricana','CENTROAFRICANA','CAF');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaCheca','CHECA','CZE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicadeMacedonia','MACEDONIA','MKD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicadelCongo','CONGOLEÑA','COG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaDemocráticadelCongo','CONGOLEÑA','COD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaDominicana','DOMINICANA','DOM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaSudafricana','SUDAFRICANA','ZAF');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ruanda','RUANDÉSA','RWA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Rumanía','RUMANA','ROU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Rusia','RUSA','RUS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Samoa','SAMOANA','WSM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanCristóbalyNieves','CRISTOBALEÑA','KNA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanMarino','SANMARINENSE','SMR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanVicenteylasGranadinas','SANVICENTINA','VCT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SantaLucía','SANTALUCENSE','LCA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SantoToméyPríncipe','SANTOTOMENSE','STP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Senegal','SENEGALÉSA','SEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Serbia','SERBIA','SRB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Seychelles','SEYCHELLENSE','SYC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SierraLeona','SIERRALEONÉSA','SLE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Singapur','SINGAPURENSE','SGP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Siria','SIRIA','SYR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Somalia','SOMALÍ','SOM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SriLanka','CEILANÉSA','LKA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Suazilandia','SUAZI','SWZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SudándelSur','SURSUDANÉSA','SSD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Sudán','SUDANÉSA','SDN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Suecia','SUECA','SWE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Suiza','SUIZA','CHE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Surinam','SURINAMESA','SUR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Tailandia','TAILANDÉSA','THA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Tanzania','TANZANA','TZA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Tayikistán','TAYIKA','TJK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('TimorOriental','TIMORENSE','TLS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Togo','TOGOLÉSA','TGO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Tonga','TONGANA','TON');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('TrinidadyTobago','TRINITENSE','TTO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Túnez','TUNECINA','TUN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Turkmenistán','TURCOMANA','TKM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Turquía','TURCA','TUR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Tuvalu','TUVALUANA','TUV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ucrania','UCRANIANA','UKR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Uganda','UGANDÉSA','UGA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Uruguay','URUGUAYA','URY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Uzbekistán','UZBEKA','UZB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Vanuatu','VANUATUENSE','VUT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Venezuela','VENEZOLANA','VEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Vietnam','VIETNAMITA','VNM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Yemen','YEMENÍ','YEM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Yibuti','YIBUTIANA','DJI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Zambia','ZAMBIANA','ZMB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Zimbabue','ZIMBABUENSE','ZWE');
#####################################################################################################


##################### INSERSECIÓN DE PRONVINCIAS, CANTONES Y DISTRITOS ####################
Insert into provincias values(1,' SAN JOSE');
Insert into cantones values (1,'01',' SAN JOSE');
Insert into distritos values (1,'01','01','Carmen');
Insert into distritos values (1,'01','02','Merced');
Insert into distritos values (1,'01','03','Hospital');
Insert into distritos values (1,'01','04','Catedral');
Insert into distritos values (1,'01','05','Zapote');
Insert into distritos values (1,'01','06','San Francisco de Dos Ríos');
Insert into distritos values (1,'01','07','Uruca');
Insert into distritos values (1,'01','08','Mata Redonda');
Insert into distritos values (1,'01','09','Pavas');
Insert into distritos values (1,'01','10','Hatillo');
Insert into distritos values (1,'01','11','San Sebastián');
Insert into cantones values (1,'02',' ESCAZU');
Insert into distritos values (1,'02','01','Escazú');
Insert into distritos values (1,'02','02','San Antonio');
Insert into distritos values (1,'02','03','San Rafael');
Insert into cantones values (1,'03',' DESAMPARADOS');
Insert into distritos values (1,'03','01','Desamparados');
Insert into distritos values (1,'03','02','San Miguel');
Insert into distritos values (1,'03','03','San Juan de Dios');
Insert into distritos values (1,'03','04','San Rafael Arriba');
Insert into distritos values (1,'03','05','San Antonio');
Insert into distritos values (1,'03','06','Frailes');
Insert into distritos values (1,'03','07','Patarrá');
Insert into distritos values (1,'03','08','San Cristóbal');
Insert into distritos values (1,'03','09','Rosario');
Insert into distritos values (1,'03','10','Damas');
Insert into distritos values (1,'03','11','San Rafael Abajo');
Insert into distritos values (1,'03','12','Gravilias');
Insert into distritos values (1,'03','13','Los Guido');
Insert into cantones values (1,'04',' PURISCAL');
Insert into distritos values (1,'04','01','Santiago');
Insert into distritos values (1,'04','02','Mercedes Sur');
Insert into distritos values (1,'04','03','Barbacoas');
Insert into distritos values (1,'04','04','Grifo Alto');
Insert into distritos values (1,'04','05','San Rafael');
Insert into distritos values (1,'04','06','Candelarita');
Insert into distritos values (1,'04','07','Desamparaditos');
Insert into distritos values (1,'04','08','San Antonio');
Insert into distritos values (1,'04','09','Chires');
Insert into distritos values (1,'04','10','La Cangreja');
Insert into cantones values (1,'05',' TARRAZU');
Insert into distritos values (1,'05','01','San Marcos');
Insert into distritos values (1,'05','02','San Lorenzo');
Insert into distritos values (1,'05','03','San Carlos');
Insert into cantones values (1,'06',' ASERRI');
Insert into distritos values (1,'06','01','Aserrí');
Insert into distritos values (1,'06','02','Tarbaca o Praga');
Insert into distritos values (1,'06','03','Vuelta de Jorco');
Insert into distritos values (1,'06','04','San Gabriel');
Insert into distritos values (1,'06','05','La Legua');
Insert into distritos values (1,'06','06','Monterrey');
Insert into distritos values (1,'06','07','Salitrillos');
Insert into cantones values (1,'07',' MORA');
Insert into distritos values (1,'07','01','Ciudad Colón');
Insert into distritos values (1,'07','02','Guayabo');
Insert into distritos values (1,'07','03','Tabarcia');
Insert into distritos values (1,'07','04','Piedras Negras');
Insert into distritos values (1,'07','05','Picagres');
Insert into distritos values (1,'07','06','Jaris');
Insert into distritos values (1,'07','07','Quitirrisi');
Insert into cantones values (1,'08',' GOICOECHEA');
Insert into distritos values (1,'08','01','Guadalupe');
Insert into distritos values (1,'08','02','San Francisco');
Insert into distritos values (1,'08','03','Calle Blancos');
Insert into distritos values (1,'08','04','Mata de Plátano');
Insert into distritos values (1,'08','05','Ipís');
Insert into distritos values (1,'08','06','Rancho Redondo');
Insert into distritos values (1,'08','07','Purral');
Insert into cantones values (1,'09',' SANTA ANA');
Insert into distritos values (1,'09','01','Santa Ana');
Insert into distritos values (1,'09','02','Salitral');
Insert into distritos values (1,'09','03','Pozos o Concepción');
Insert into distritos values (1,'09','04','Uruca o San Joaquín');
Insert into distritos values (1,'09','05','Piedades');
Insert into distritos values (1,'09','06','Brasil');
Insert into cantones values (1,'10',' ALAJUELITA');
Insert into distritos values (1,'10','01','Alajuelita');
Insert into distritos values (1,'10','02','San Josecito');
Insert into distritos values (1,'10','03','San Antonio');
Insert into distritos values (1,'10','04','Concepción');
Insert into distritos values (1,'10','05','San Felipe');
Insert into cantones values (1,'11',' CORONADO');
Insert into distritos values (1,'11','01','San Isidro');
Insert into distritos values (1,'11','02','San Rafael');
Insert into distritos values (1,'11','03','Dulce Nombre o Jesús');
Insert into distritos values (1,'11','04','Patalillo');
Insert into distritos values (1,'11','05','Cascajal');
Insert into cantones values (1,'12',' ACOSTA');
Insert into distritos values (1,'12','01','San Ignacio');
Insert into distritos values (1,'12','02','Guaitil');
Insert into distritos values (1,'12','03','Palmichal');
Insert into distritos values (1,'12','04','Cangrejal');
Insert into distritos values (1,'12','05','Sabanillas');
Insert into cantones values (1,'13',' TIBAS');
Insert into distritos values (1,'13','01','San Juan');
Insert into distritos values (1,'13','02','Cinco Esquinas');
Insert into distritos values (1,'13','03','Anselmo Llorente');
Insert into distritos values (1,'13','04','León XIII');
Insert into distritos values (1,'13','05','Colima');
Insert into cantones values (1,'14',' MORAVIA');
Insert into distritos values (1,'14','01','San Vicente');
Insert into distritos values (1,'14','02','San Jerónimo');
Insert into distritos values (1,'14','03','La Trinidad');
Insert into cantones values (1,'15',' MONTES DE OCA');
Insert into distritos values (1,'15','01','San Pedro');
Insert into distritos values (1,'15','02','Sabanilla');
Insert into distritos values (1,'15','03','Mercedes o Betania');
Insert into distritos values (1,'15','04','San Rafael');
Insert into cantones values (1,'16',' TURRUBARES');
Insert into distritos values (1,'16','01','San Pablo');
Insert into distritos values (1,'16','02','San Pedro');
Insert into distritos values (1,'16','03','San Juan de Mata');
Insert into distritos values (1,'16','04','San Luis');
Insert into distritos values (1,'16','05','Carara');
Insert into cantones values (1,'17',' DOTA');
Insert into distritos values (1,'17','01','Santa María');
Insert into distritos values (1,'17','02','Jardín');
Insert into distritos values (1,'17','03','Copey');
Insert into cantones values (1,'18',' CURRIDABAT');
Insert into distritos values (1,'18','01','Curridabat');
Insert into distritos values (1,'18','02','Granadilla');
Insert into distritos values (1,'18','03','Sánchez');
Insert into distritos values (1,'18','04','Tirrases');
Insert into cantones values (1,'19',' PEREZ ZELEDON');
Insert into distritos values (1,'19','01','San Isidro de El General');
Insert into distritos values (1,'19','02','General');
Insert into distritos values (1,'19','03','Daniel Flores');
Insert into distritos values (1,'19','04','Rivas');
Insert into distritos values (1,'19','05','San Pedro');
Insert into distritos values (1,'19','06','Platanares');
Insert into distritos values (1,'19','07','Pejibaye');
Insert into distritos values (1,'19','08','Cajón o Carmen');
Insert into distritos values (1,'19','09','Barú');
Insert into distritos values (1,'19','10','Río Nuevo');
Insert into distritos values (1,'19','11','Páramo');
Insert into distritos values (1,'19','12','La Amistad');
Insert into cantones values (1,'20',' LEON CORTES');
Insert into distritos values (1,'20','01','San Pablo');
Insert into distritos values (1,'20','02','San Andrés');
Insert into distritos values (1,'20','03','Llano Bonito');
Insert into distritos values (1,'20','04','San Isidro');
Insert into distritos values (1,'20','05','Santa Cruz');
Insert into distritos values (1,'20','06','San Antonio');
Insert into provincias values(2,' ALAJUELA');
Insert into cantones values (2,'01',' ALAJUELA');
Insert into distritos values (2,'01','01','Alajuela');
Insert into distritos values (2,'01','02','San José');
Insert into distritos values (2,'01','03','Carrizal');
Insert into distritos values (2,'01','04','San Antonio');
Insert into distritos values (2,'01','05','Guácima');
Insert into distritos values (2,'01','06','San Isidro');
Insert into distritos values (2,'01','07','Sabanilla');
Insert into distritos values (2,'01','08','San Rafael');
Insert into distritos values (2,'01','09','Río Segundo');
Insert into distritos values (2,'01','10','Desamparados');
Insert into distritos values (2,'01','11','Turrucares');
Insert into distritos values (2,'01','12','Tambor');
Insert into distritos values (2,'01','13','La Garita');
Insert into distritos values (2,'01','14','Sarapiquí');
Insert into cantones values (2,'02',' SAN RAMON');
Insert into distritos values (2,'02','01','San Ramón');
Insert into distritos values (2,'02','02','Santiago');
Insert into distritos values (2,'02','03','San Juan');
Insert into distritos values (2,'02','04','Piedades Norte');
Insert into distritos values (2,'02','05','Piedades Sur');
Insert into distritos values (2,'02','06','San Rafael');
Insert into distritos values (2,'02','07','San Isidro');
Insert into distritos values (2,'02','08','Angeles');
Insert into distritos values (2,'02','09','Alfaro');
Insert into distritos values (2,'02','10','Volio');
Insert into distritos values (2,'02','11','Concepción');
Insert into distritos values (2,'02','12','Zapotal');
Insert into distritos values (2,'02','13','San Isidro de Peñas Blancas');
Insert into distritos values (2,'02','14','San Lorenzo');
Insert into cantones values (2,'03','  GRECIA');
Insert into distritos values (2,'03','01','Grecia');
Insert into distritos values (2,'03','02','San Isidro');
Insert into distritos values (2,'03','03','San José');
Insert into distritos values (2,'03','04','San Roque');
Insert into distritos values (2,'03','05','Tacares');
Insert into distritos values (2,'03','06','Puente Piedra');
Insert into distritos values (2,'03','07','Bolívar');
Insert into cantones values (2,'04',' SAN MATEO');
Insert into distritos values (2,'04','01','San Mateo');
Insert into distritos values (2,'04','02','Desmonte');
Insert into distritos values (2,'04','03','Jesús María');
Insert into distritos values (2,'04','04','Labrador');
Insert into cantones values (2,'05',' ATENAS');
Insert into distritos values (2,'05','01','Atenas');
Insert into distritos values (2,'05','02','Jesús');
Insert into distritos values (2,'05','03','Mercedes');
Insert into distritos values (2,'05','04','San Isidro');
Insert into distritos values (2,'05','05','Concepción');
Insert into distritos values (2,'05','06','San José');
Insert into distritos values (2,'05','07','Santa Eulalia');
Insert into distritos values (2,'05','08','Escobal');
Insert into cantones values (2,'06',' NARANJO');
Insert into distritos values (2,'06','01','Naranjo');
Insert into distritos values (2,'06','02','San Miguel');
Insert into distritos values (2,'06','03','San José');
Insert into distritos values (2,'06','04','Cirrí Sur');
Insert into distritos values (2,'06','05','San Jerónimo');
Insert into distritos values (2,'06','06','San Juan');
Insert into distritos values (2,'06','07','Rosario');
Insert into cantones values (2,'07',' PALMARES');
Insert into distritos values (2,'07','01','Palmares');
Insert into distritos values (2,'07','02','Zaragoza');
Insert into distritos values (2,'07','03','Buenos Aires');
Insert into distritos values (2,'07','04','Santiago');
Insert into distritos values (2,'07','05','Candelaria');
Insert into distritos values (2,'07','06','Esquipulas');
Insert into distritos values (2,'07','07','La Granja');
Insert into cantones values (2,'08',' POAS');
Insert into distritos values (2,'08','01','San Pedro');
Insert into distritos values (2,'08','02','San Juan');
Insert into distritos values (2,'08','03','San Rafael');
Insert into distritos values (2,'08','04','Carrillos');
Insert into distritos values (2,'08','05','Sabana Redonda');
Insert into cantones values (2,'09',' OROTINA');
Insert into distritos values (2,'09','01','Orotina');
Insert into distritos values (2,'09','02','Mastate');
Insert into distritos values (2,'09','03','Hacienda Vieja');
Insert into distritos values (2,'09','04','Coyolar');
Insert into distritos values (2,'09','05','Ceiba');
Insert into cantones values (2,'10',' SAN CARLOS');
Insert into distritos values (2,'10','01','Quesada');
Insert into distritos values (2,'10','02','Florencia');
Insert into distritos values (2,'10','03','Buenavista');
Insert into distritos values (2,'10','04','Aguas Zarcas');
Insert into distritos values (2,'10','05','Venecia');
Insert into distritos values (2,'10','06','Pital');
Insert into distritos values (2,'10','07','Fortuna');
Insert into distritos values (2,'10','08','Tigra');
Insert into distritos values (2,'10','09','Palmera');
Insert into distritos values (2,'10','10','Venado');
Insert into distritos values (2,'10','11','Cutris');
Insert into distritos values (2,'10','12','Monterrey');
Insert into distritos values (2,'10','13','Pocosol');
Insert into cantones values (2,'11',' ALFARO RUIZ');
Insert into distritos values (2,'11','01','Zarcero');
Insert into distritos values (2,'11','02','Laguna');
Insert into distritos values (2,'11','03','Tapezco');
Insert into distritos values (2,'11','04','Guadalupe');
Insert into distritos values (2,'11','05','Palmira');
Insert into distritos values (2,'11','06','Zapote');
Insert into distritos values (2,'11','07','Brisas');
Insert into cantones values (2,'12',' VALVERDE VEGA');
Insert into distritos values (2,'12','01','Sarchí Norte');
Insert into distritos values (2,'12','02','Sarchí Sur');
Insert into distritos values (2,'12','03','Toro Amarillo');
Insert into distritos values (2,'12','04','San Pedro');
Insert into distritos values (2,'12','05','Rodríguez');
Insert into cantones values (2,'13',' UPALA');
Insert into distritos values (2,'13','01','Upala');
Insert into distritos values (2,'13','02','Aguas Claras');
Insert into distritos values (2,'13','03','San José o Pizote');
Insert into distritos values (2,'13','04','Bijagua');
Insert into distritos values (2,'13','05','Delicias');
Insert into distritos values (2,'13','06','Dos Ríos');
Insert into distritos values (2,'13','07','Yolillal');
Insert into distritos values (2,'13','08','Canalete');
Insert into cantones values (2,'14',' LOS CHILES');
Insert into distritos values (2,'14','01','Los Chiles');
Insert into distritos values (2,'14','02','Caño Negro');
Insert into distritos values (2,'14','03','Amparo');
Insert into distritos values (2,'14','04','San Jorge');
Insert into cantones values (2,'15',' GUATUSO');
Insert into distritos values (2,'15','01','San Rafael');
Insert into distritos values (2,'15','02','Buenavista');
Insert into distritos values (2,'15','03','Cote');
Insert into distritos values (2,'15','04','Katira');
Insert into cantones values (2,'16',' RIO CUARTO');
Insert into distritos values (2,'16','01','Rio Cuarto');
Insert into provincias values(3,' CARTAGO');
Insert into cantones values (3,'01',' CARTAGO');
Insert into distritos values (3,'01','01','Oriental');
Insert into distritos values (3,'01','02','Occidental');
Insert into distritos values (3,'01','03','Carmen');
Insert into distritos values (3,'01','04','San Nicolás');
Insert into distritos values (3,'01','05','Aguacaliente  (San Francisco);');
Insert into distritos values (3,'01','06','Guadalupe  (Arenilla);');
Insert into distritos values (3,'01','07','Corralillo');
Insert into distritos values (3,'01','08','Tierra Blanca');
Insert into distritos values (3,'01','09','Dulce Nombre');
Insert into distritos values (3,'01','10','Llano Grande');
Insert into distritos values (3,'01','11','Quebradilla');
Insert into cantones values (3,'02',' PARAISO');
Insert into distritos values (3,'02','01','Paraíso');
Insert into distritos values (3,'02','02','Santiago');
Insert into distritos values (3,'02','03','Orosi');
Insert into distritos values (3,'02','04','Cachí');
Insert into distritos values (3,'02','05','Llanos de Sta Lucia');
Insert into cantones values (3,'03',' LA UNION');
Insert into distritos values (3,'03','01','Tres Ríos');
Insert into distritos values (3,'03','02','San Diego');
Insert into distritos values (3,'03','03','San Juan');
Insert into distritos values (3,'03','04','San Rafael');
Insert into distritos values (3,'03','05','Concepción');
Insert into distritos values (3,'03','06','Dulce Nombre');
Insert into distritos values (3,'03','07','San Ramón');
Insert into distritos values (3,'03','08','Río Azul');
Insert into cantones values (3,'04',' JIMENEZ');
Insert into distritos values (3,'04','01','Juan Viñas');
Insert into distritos values (3,'04','02','Tucurrique');
Insert into distritos values (3,'04','03','Pejibaye');
Insert into cantones values (3,'05',' TURRIALBA');
Insert into distritos values (3,'05','01','Turrialba');
Insert into distritos values (3,'05','02','La Suiza');
Insert into distritos values (3,'05','03','Peralta');
Insert into distritos values (3,'05','04','Santa Cruz');
Insert into distritos values (3,'05','05','Santa Teresita');
Insert into distritos values (3,'05','06','Pavones');
Insert into distritos values (3,'05','07','Tuis');
Insert into distritos values (3,'05','08','Tayutic');
Insert into distritos values (3,'05','09','Santa Rosa');
Insert into distritos values (3,'05','10','Tres Equis');
Insert into distritos values (3,'05','11','La Isabel');
Insert into distritos values (3,'05','12','Chirripo');
Insert into cantones values (3,'06',' ALVARADO');
Insert into distritos values (3,'06','01','Pacayas');
Insert into distritos values (3,'06','02','Cervantes');
Insert into distritos values (3,'06','03','Capellades');
Insert into cantones values (3,'07',' OREAMUNO');
Insert into distritos values (3,'07','01','San Rafael');
Insert into distritos values (3,'07','02','Cot');
Insert into distritos values (3,'07','03','Potrero Cerrado');
Insert into distritos values (3,'07','04','Cipreses');
Insert into distritos values (3,'07','05','Santa Rosa');
Insert into cantones values (3,'08',' EL GUARCO');
Insert into distritos values (3,'08','01','El Tejar');
Insert into distritos values (3,'08','02','San Isidro');
Insert into distritos values (3,'08','03','Tobosi');
Insert into distritos values (3,'08','04','Patio de Agua');
Insert into provincias values(4,' HEREDIA');
Insert into cantones values (4,'01',' HEREDIA');
Insert into distritos values (4,'01','01','Heredia');
Insert into distritos values (4,'01','02','Mercedes');
Insert into distritos values (4,'01','03','San Francisco');
Insert into distritos values (4,'01','04','Ulloa');
Insert into distritos values (4,'01','05','Vara Blanca');
Insert into cantones values (4,'02',' BARVA');
Insert into distritos values (4,'02','01','Barva');
Insert into distritos values (4,'02','02','San Pedro');
Insert into distritos values (4,'02','03','San Pablo');
Insert into distritos values (4,'02','04','San Roque');
Insert into distritos values (4,'02','05','Santa Lucía');
Insert into distritos values (4,'02','06','San José de la Montaña');
Insert into cantones values (4,'03',' SANTO DOMINGO');
Insert into distritos values (4,'03','01','Santo Domingo');
Insert into distritos values (4,'03','02','San Vicente');
Insert into distritos values (4,'03','03','San Miguel');
Insert into distritos values (4,'03','04','Paracito');
Insert into distritos values (4,'03','05','Santo Tomás');
Insert into distritos values (4,'03','06','Santa Rosa');
Insert into distritos values (4,'03','07','Tures');
Insert into distritos values (4,'03','08','Pará');
Insert into cantones values (4,'04',' SANTA BARBARA');
Insert into distritos values (4,'04','01','Santa Bárbara');
Insert into distritos values (4,'04','02','San Pedro');
Insert into distritos values (4,'04','03','San Juan');
Insert into distritos values (4,'04','04','Jesús');
Insert into distritos values (4,'04','05','Santo Domingo del Roble');
Insert into distritos values (4,'04','06','Puraba');
Insert into cantones values (4,'05',' SAN RAFAEL');
Insert into distritos values (4,'05','01','San Rafael');
Insert into distritos values (4,'05','02','San Josecito');
Insert into distritos values (4,'05','03','Santiago');
Insert into distritos values (4,'05','04','Angeles');
Insert into distritos values (4,'05','05','Concepción');
Insert into cantones values (4,'06',' SAN ISIDRO');
Insert into distritos values (4,'06','01','San Isidro');
Insert into distritos values (4,'06','02','San José');
Insert into distritos values (4,'06','03','Concepción');
Insert into distritos values (4,'06','04','San Francisco');
Insert into cantones values (4,'07',' BELEN');
Insert into distritos values (4,'07','01','San Antonio');
Insert into distritos values (4,'07','02','La Rivera');
Insert into distritos values (4,'07','03','Asunción');
Insert into cantones values (4,'08',' FLORES');
Insert into distritos values (4,'08','01','San Joaquín');
Insert into distritos values (4,'08','02','Barrantes');
Insert into distritos values (4,'08','03','Llorente');
Insert into cantones values (4,'09',' SAN PABLO');
Insert into distritos values (4,'09','01','San Pablo');
Insert into distritos values (4,'09','02','Rincon de Sabanilla');
Insert into cantones values (4,'10',' SARAPIQUI');
Insert into distritos values (4,'10','01','Puerto Viejo');
Insert into distritos values (4,'10','02','La Virgen');
Insert into distritos values (4,'10','03','Horquetas');
Insert into distritos values (4,'10','04','Llanuras del Gaspar');
Insert into distritos values (4,'10','05','Cureña');
Insert into provincias values(5,' GUANACASTE');
Insert into cantones values (5,'01',' LIBERIA');
Insert into distritos values (5,'01','01','Liberia');
Insert into distritos values (5,'01','02','Cañas Dulces');
Insert into distritos values (5,'01','03','Mayorga');
Insert into distritos values (5,'01','04','Nacascolo');
Insert into distritos values (5,'01','05','Curubande');
Insert into cantones values (5,'02',' NICOYA');
Insert into distritos values (5,'02','01','Nicoya');
Insert into distritos values (5,'02','02','Mansión');
Insert into distritos values (5,'02','03','San Antonio');
Insert into distritos values (5,'02','04','Quebrada Honda');
Insert into distritos values (5,'02','05','Sámara');
Insert into distritos values (5,'02','06','Nosara');
Insert into distritos values (5,'02','07','Belén de Nosarita');
Insert into cantones values (5,'03',' SANTA CRUZ');
Insert into distritos values (5,'03','01','Santa Cruz');
Insert into distritos values (5,'03','02','Bolsón');
Insert into distritos values (5,'03','03','Veintisiete de Abril');
Insert into distritos values (5,'03','04','Tempate');
Insert into distritos values (5,'03','05','Cartagena');
Insert into distritos values (5,'03','06','Cuajiniquil');
Insert into distritos values (5,'03','07','Diriá');
Insert into distritos values (5,'03','08','Cabo Velas');
Insert into distritos values (5,'03','09','Tamarindo');
Insert into cantones values (5,'04',' BAGACES');
Insert into distritos values (5,'04','01','Bagaces');
Insert into distritos values (5,'04','02','Fortuna');
Insert into distritos values (5,'04','03','Mogote');
Insert into distritos values (5,'04','04','Río Naranjo');
Insert into cantones values (5,'05',' CARRILLO');
Insert into distritos values (5,'05','01','Filadelfia');
Insert into distritos values (5,'05','02','Palmira');
Insert into distritos values (5,'05','03','Sardinal');
Insert into distritos values (5,'05','04','Belén');
Insert into cantones values (5,'06',' CAÑAS');
Insert into distritos values (5,'06','01','Cañas');
Insert into distritos values (5,'06','02','Palmira');
Insert into distritos values (5,'06','03','San Miguel');
Insert into distritos values (5,'06','04','Bebedero');
Insert into distritos values (5,'06','05','Porozal');
Insert into cantones values (5,'07',' ABANGARES');
Insert into distritos values (5,'07','01','Juntas');
Insert into distritos values (5,'07','02','Sierra');
Insert into distritos values (5,'07','03','San Juan');
Insert into distritos values (5,'07','04','Colorado');
Insert into cantones values (5,'08',' TILARAN');
Insert into distritos values (5,'08','01','Tilarán');
Insert into distritos values (5,'08','02','Quebrada Grande');
Insert into distritos values (5,'08','03','Tronadora');
Insert into distritos values (5,'08','04','Santa Rosa');
Insert into distritos values (5,'08','05','Líbano');
Insert into distritos values (5,'08','06','Tierras Morenas');
Insert into distritos values (5,'08','07','Arenal');
Insert into cantones values (5,'09',' NANDAYURE');
Insert into distritos values (5,'09','01','Carmona');
Insert into distritos values (5,'09','02','Santa Rita');
Insert into distritos values (5,'09','03','Zapotal');
Insert into distritos values (5,'09','04','San Pablo');
Insert into distritos values (5,'09','05','Porvenir');
Insert into distritos values (5,'09','06','Bejuco');
Insert into cantones values (5,'10',' LA CRUZ');
Insert into distritos values (5,'10','01','La Cruz');
Insert into distritos values (5,'10','02','Santa Cecilia');
Insert into distritos values (5,'10','03','Garita');
Insert into distritos values (5,'10','04','Santa Elena');
Insert into cantones values (5,'11',' HOJANCHA');
Insert into distritos values (5,'11','01','Hojancha');
Insert into distritos values (5,'11','02','Monte Romo');
Insert into distritos values (5,'11','03','Puerto Carrillo');
Insert into distritos values (5,'11','04','Huacas');
Insert into distritos values (5,'11','05','Matambú');
Insert into provincias values(6,' PUNTARENAS');
Insert into cantones values (6,'01',' PUNTARENAS');
Insert into distritos values (6,'01','01','Puntarenas');
Insert into distritos values (6,'01','02','Pitahaya');
Insert into distritos values (6,'01','03','Chomes');
Insert into distritos values (6,'01','04','Lepanto');
Insert into distritos values (6,'01','05','Paquera');
Insert into distritos values (6,'01','06','Manzanillo');
Insert into distritos values (6,'01','07','Guacimal');
Insert into distritos values (6,'01','08','Barranca');
Insert into distritos values (6,'01','09','Monte Verde');
Insert into distritos values (6,'01','10','Isla del Coco');
Insert into distritos values (6,'01','11','Cóbano');
Insert into distritos values (6,'01','12','Chacarita');
Insert into distritos values (6,'01','13','Chira (Isla);');
Insert into distritos values (6,'01','14','Acapulco');
Insert into distritos values (6,'01','15','El Roble');
Insert into distritos values (6,'01','16','Arancibia');
Insert into cantones values (6,'02',' ESPARZA');
Insert into distritos values (6,'02','01','Espíritu Santo');
Insert into distritos values (6,'02','02','San Juan Grande');
Insert into distritos values (6,'02','03','Macacona');
Insert into distritos values (6,'02','04','San Rafael');
Insert into distritos values (6,'02','05','San Jerónimo');
Insert into distritos values (6,'02','06','Caldera');
Insert into cantones values (6,'03',' BUENOS AIRES');
Insert into distritos values (6,'03','01','Buenos Aires');
Insert into distritos values (6,'03','02','Volcán');
Insert into distritos values (6,'03','03','Potrero Grande');
Insert into distritos values (6,'03','04','Boruca');
Insert into distritos values (6,'03','05','Pilas');
Insert into distritos values (6,'03','06','Colinas o Bajo de Maíz');
Insert into distritos values (6,'03','07','Chánguena');
Insert into distritos values (6,'03','08','Biolley');
Insert into distritos values (6,'03','09','Brunka');
Insert into cantones values (6,'04',' MONTES DE ORO');
Insert into distritos values (6,'04','01','Miramar');
Insert into distritos values (6,'04','02','Unión');
Insert into distritos values (6,'04','03','San Isidro');
Insert into cantones values (6,'05',' OSA');
Insert into distritos values (6,'05','01','Ciudad Cortés');
Insert into distritos values (6,'05','02','Palmar');
Insert into distritos values (6,'05','03','Sierpe');
Insert into distritos values (6,'05','04','Bahía Ballena');
Insert into distritos values (6,'05','05','Piedras Blancas');
Insert into distritos values (6,'05','06','Bahia Drake');
Insert into cantones values (6,'06',' AGUIRRE');
Insert into distritos values (6,'06','01','Quepos');
Insert into distritos values (6,'06','02','Savegre');
Insert into distritos values (6,'06','03','Naranjito');
Insert into cantones values (6,'07',' GOLFITO');
Insert into distritos values (6,'07','01','Golfito');
Insert into distritos values (6,'07','02','Puerto Jiménez');
Insert into distritos values (6,'07','03','Guaycará');
Insert into distritos values (6,'07','04','Pavones o Villa Conte');
Insert into cantones values (6,'08',' COTO BRUS');
Insert into distritos values (6,'08','01','San Vito');
Insert into distritos values (6,'08','02','Sabalito');
Insert into distritos values (6,'08','03','Agua Buena');
Insert into distritos values (6,'08','04','Limoncito');
Insert into distritos values (6,'08','05','Pittier');
Insert into distritos values (6,'08','06','Gutierrez Brown');
Insert into cantones values (6,'09',' PARRITA');
Insert into distritos values (6,'09','01','Parrita');
Insert into cantones values (6,'10',' CORREDORES');
Insert into distritos values (6,'10','01','Corredores');
Insert into distritos values (6,'10','02','La Cuesta');
Insert into distritos values (6,'10','03','Paso Canoas');
Insert into distritos values (6,'10','04','Laurel');
Insert into cantones values (6,'11',' GARABITO');
Insert into distritos values (6,'11','01','Jacó');
Insert into distritos values (6,'11','02','Tárcoles');
Insert into provincias values(7,' LIMON');
Insert into cantones values (7,'01',' LIMON');
Insert into distritos values (7,'01','01','Limón');
Insert into distritos values (7,'01','02','Valle  La Estrella');
Insert into distritos values (7,'01','03','Río Blanco');
Insert into distritos values (7,'01','04','Matama');
Insert into cantones values (7,'02',' POCOCI');
Insert into distritos values (7,'02','01','Guápiles');
Insert into distritos values (7,'02','02','Jiménez');
Insert into distritos values (7,'02','03','Rita');
Insert into distritos values (7,'02','04','Roxana');
Insert into distritos values (7,'02','05','Cariari');
Insert into distritos values (7,'02','06','Colorado');
Insert into distritos values (7,'02','07','La Colonia');
Insert into cantones values (7,'03',' SIQUIRRES');
Insert into distritos values (7,'03','01','Siquirres');
Insert into distritos values (7,'03','02','Pacuarito');
Insert into distritos values (7,'03','03','Florida');
Insert into distritos values (7,'03','04','Germania');
Insert into distritos values (7,'03','05','Cairo');
Insert into distritos values (7,'03','06','Alegría');
Insert into cantones values (7,'04',' TALAMANCA');
Insert into distritos values (7,'04','01','Bratsi');
Insert into distritos values (7,'04','02','Sixaola');
Insert into distritos values (7,'04','03','Cahuita');
Insert into distritos values (7,'04','04','Telire');
Insert into cantones values (7,'05',' MATINA');
Insert into distritos values (7,'05','01','Matina');
Insert into distritos values (7,'05','02','Batán');
Insert into distritos values (7,'05','03','Carrandí');
Insert into cantones values (7,'06',' GUACIMO');
Insert into distritos values (7,'06','01','Guácimo');
Insert into distritos values (7,'06','02','Mercedes');
Insert into distritos values (7,'06','03','Pocora');
Insert into distritos values (7,'06','04','Río Jiménez');
Insert into distritos values (7,'06','05','Duacarí');
##################### INSERSECIÓN DE PRONVINCIAS, CANTONES Y DISTRITOS ####################


######################################## PARÁMETROS DEL COLEGIO ####################################
insert into parametros_colegio values('CINDEA JUDAS','6519','MSc. Luis Fernando Elizondo Carrillo');
#####################################################################################################


######################################## SATÉLITES ####################################
insert into satelites values('01','SEDE CENTRAL');
insert into satelites values('02','COSTA DE PÁJAROS');
insert into satelites values('03','CHOMES');
#####################################################################################################


######################################## PERIODOS PRECARGADOS HASTA EL 2024 ####################################
insert into periodos_academicos values('2015','1','0');
insert into periodos_academicos values('2015','2','0');
insert into periodos_academicos values('2016','1','0');
insert into periodos_academicos values('2016','2','0');
insert into periodos_academicos values('2017','1','0');
insert into periodos_academicos values('2017','2','0');
insert into periodos_academicos values('2018','1','0');
insert into periodos_academicos values('2018','2','0');
insert into periodos_academicos values('2019','1','0');
insert into periodos_academicos values('2019','2','0');
insert into periodos_academicos values('2020','1','0');
insert into periodos_academicos values('2020','2','0');
insert into periodos_academicos values('2021','1','0');
insert into periodos_academicos values('2021','2','0');
insert into periodos_academicos values('2022','1','0');
insert into periodos_academicos values('2022','2','0');
insert into periodos_academicos values('2023','1','0');
insert into periodos_academicos values('2023','2','0');
insert into periodos_academicos values('2024','1','0');
insert into periodos_academicos values('2024','2','0');
##......................############
#####################################################################################################


######################################## ADECUACIONES ####################################
insert into adecuaciones values('01','NO REQUIERE');
insert into adecuaciones values('02','SIGNIFICATIVA');
insert into adecuaciones values('03','NO SIGNIFICATIVA');
insert into adecuaciones values('04','ACCESO');
#####################################################################################################


######################################## GRUPO PROFESIONAL DOCENTES ####################################
insert into grupo_profesional_doc values('ASP','PROFESOR ASPIRANTE');
insert into grupo_profesional_doc values('KAU-1','PROFESOR EN ENSEÑANZA PRESCOLAR AUTORIZADO');
insert into grupo_profesional_doc values('KAU-2','PROFESOR EN ENSEÑANZA PRESCOLAR AUTORIZADO');
insert into grupo_profesional_doc values('KAU-3','PROFESOR EN ENSEÑANZA PRESCOLAR AUTORIZADO');
insert into grupo_profesional_doc values('KAU-4','PROFESOR EN ENSEÑANZA PRESCOLAR AUTORIZADO');
insert into grupo_profesional_doc values('KT-1','PROFESOR EN ENSEÑANZA PRESCOLAR TITULADO');
insert into grupo_profesional_doc values('KT-2','PROFESOR EN ENSEÑANZA PRESCOLAR TITULADO');
insert into grupo_profesional_doc values('KT-4','PROFESOR EN ENSEÑANZA PRESCOLAR TITULADO');
insert into grupo_profesional_doc values('PAU-1','PROFESOR EN ENSEÑANZA PRIMARIA AUTORIZADO');
insert into grupo_profesional_doc values('PAU-2','PROFESOR EN ENSEÑANZA PRIMARIA AUTORIZADO');
insert into grupo_profesional_doc values('PT-1','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('PT-2','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('PT-3','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('PT-4','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('PT-5','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('PT-6','PROFESOR EN ENSEÑANZA PRIMARIA TITULADO');
insert into grupo_profesional_doc values('MAU-1','PROFESOR EN ENSEÑANZA MEDIA AUTORIZADO');
insert into grupo_profesional_doc values('MAU-2','PROFESOR EN ENSEÑANZA MEDIA AUTORIZADO');
insert into grupo_profesional_doc values('MT-1','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('MT-2','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('MT-3','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('MT-4','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('MT-5','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('MT-6','PROFESOR EN ENSEÑANZA MEDIA TITULADO');
insert into grupo_profesional_doc values('VAU-1','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL AUTORIZADO');
insert into grupo_profesional_doc values('VAU-2','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL AUTORIZADO');
insert into grupo_profesional_doc values('VT-1','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('VT-2','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('VT-3','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('VT-4','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('VT-5','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('VT-6','PROFESOR DE ENSEÑANZA TÉCNICO PROFESIONAL TITULADO');
insert into grupo_profesional_doc values('EAU-1','PROFESOR DE ENSEÑANZA ESPECIAL AUTORIZADO');
insert into grupo_profesional_doc values('EAU-2','PROFESOR DE ENSEÑANZA ESPECIAL AUTORIZADO');
insert into grupo_profesional_doc values('ET-1','PROFESOR DE ENSEÑANZA ESPECIAL TITULADO');
insert into grupo_profesional_doc values('ET-2','PROFESOR DE ENSEÑANZA ESPECIAL TITULADO');
insert into grupo_profesional_doc values('ET-3','PROFESOR DE ENSEÑANZA ESPECIAL TITULADO');
insert into grupo_profesional_doc values('ET-4','PROFESOR DE ENSEÑANZA ESPECIAL TITULADO');
insert into grupo_profesional_doc values('NAU-1','PROFESOR AUTORIZADO DE ENSEÑANZA NORMAL');
insert into grupo_profesional_doc values('NAU-2','PROFESOR AUTORIZADO DE ENSEÑANZA NORMAL');
insert into grupo_profesional_doc values('NT-1','PROFESOR TITULADO DE ENSEÑANZA NORMAL');
insert into grupo_profesional_doc values('NT-2','PROFESOR TITULADO DE ENSEÑANZA NORMAL');
insert into grupo_profesional_doc values('NT-3','PROFESOR TITULADO DE ENSEÑANZA NORMAL');
insert into grupo_profesional_doc values('SAU-1','PROFESOR AUTORIZADO DE ENSEÑANZA SUPERIOR');
insert into grupo_profesional_doc values('SAU-2','PROFESOR AUTORIZADO DE ENSEÑANZA SUPERIOR');
insert into grupo_profesional_doc values('ST-1','PROFESOR TITULADO DE ENSEÑANZA SUPERIOR');
insert into grupo_profesional_doc values('ST-2','PROFESOR TITULADO DE ENSEÑANZA SUPERIOR');
insert into grupo_profesional_doc values('ST-3','PROFESOR TITULADO DE ENSEÑANZA SUPERIOR');
#####################################################################################################


######################################## ESPECIALIDADES DOCENTES ####################################
insert into clase_especialidad_docente values('ADMIN-AD','ADMINISTRACIÓN, LOGÍSTICA Y DISTRIBUCIÓN');
insert into clase_especialidad_docente values('SEC','SECRETARIADO');
insert into clase_especialidad_docente values('CONT','CONTABILIDAD');
insert into clase_especialidad_docente values('INF','INFORMÁTICA');
insert into clase_especialidad_docente values('CIEN','CIENCIAS');
insert into clase_especialidad_docente values('ED-FIS','EDUCACIÓN FÍSICA');
insert into clase_especialidad_docente values('PLAST','ARTES PLÁSTICAS');
insert into clase_especialidad_docente values('EN-ESP','ENSEÑANZA ESPECIAL');
insert into clase_especialidad_docente values('ESP','ESPAÑOL');
insert into clase_especialidad_docente values('EST-SOC','ESTUDIOS SOCIALES Y CÍVICA');
insert into clase_especialidad_docente values('INGLES','INGLÉS');
insert into clase_especialidad_docente values('FRAN','FRANCÉS');
insert into clase_especialidad_docente values('MUSIC','MÚSICA');
insert into clase_especialidad_docente values('PSICO','PSICOLOGÍA');
insert into clase_especialidad_docente values('TURIS','TURÍSMO');
insert into clase_especialidad_docente values('AGROEC','AGROECOLOGÍA');
insert into clase_especialidad_docente values('AGROP','AGROPECUARIA');
insert into clase_especialidad_docente values('AGROIN','AGROINDUSTRIAL');
insert into clase_especialidad_docente values('EDUC-HOG','EDUCACIÓN PARA EL HOGAR');
insert into clase_especialidad_docente values('ELECT','ELECTRÓNICA');
insert into clase_especialidad_docente values('GERON','GERONTOLOGÍA');
insert into clase_especialidad_docente values('MATE','MATEMÁTICAS');
insert into clase_especialidad_docente values('REFRIG','REFRIGERACIÓN');
insert into clase_especialidad_docente values('SALUD-OCU','SALUD OCUPACIONAL');
insert into clase_especialidad_docente values('TEATRO','TEATRO');
insert into clase_especialidad_docente values('FILOSF','FILOSOFÍA');
#####################################################################################################


################################ MODALIDADES DE ESPECIALIDADES TÉCNICAS #################################
insert into modalidades_esp values('01','AGROPECUARIO');
insert into modalidades_esp values('02','COMERCIAL Y SERVICIOS');
insert into modalidades_esp values('03','INDUSTRIAL');
#####################################################################################################


################################ ESPECIALIDADES TÉCNICAS #################################
################################ MODALIDAD AGROPECIARIA #################################
insert into especialidades values('01',UPPER('Producción Agrícola y Pecuaria'),'01');
insert into especialidades values('02',UPPER('Agropecuaria en Producción Pecuaria'),'01');
insert into especialidades values('03',UPPER('Agropecuaria en Producción Agrícola'),'01');
insert into especialidades values('04',UPPER('Agroindustria Alimentaria con Tecnología Pecuaria'),'01');
insert into especialidades values('05',UPPER('Agroindustria Alimentaria con Tecnología Agrícola'),'01');
insert into especialidades values('06',UPPER('Agro jardinería'),'01');
insert into especialidades values('07',UPPER('Agroecología'),'01');
################################ MODALIDAD COMERCIAL Y SERVICIOS #################################
insert into especialidades values('08',UPPER('Ecoturismo'),'02');
insert into especialidades values('09',UPPER('Contabilidad y Control Interno'),'02');
insert into especialidades values('10',UPPER('Operaciones de Empresas de Alojamiento'),'02');
insert into especialidades values('11',UPPER('Mercadeo'),'02');
insert into especialidades values('12',UPPER('Ejecutivo Comercial y de Servicio al Cliente'),'02');
insert into especialidades values('13',UPPER('Configuración y soporte a redes de comunicación y sistema operativos'),'02');
insert into especialidades values('14',UPPER('Turismo Rural'),'02');
insert into especialidades values('15',UPPER('Turismo en Hotelería y Eventos Especiales'),'02');
insert into especialidades values('16',UPPER('Turismo en Alimentos y Bebidas'),'02');
insert into especialidades values('17',UPPER('Turismo Ecológico'),'02');
insert into especialidades values('18',UPPER('Turismo Costero'),'02');
insert into especialidades values('19',UPPER('Secretariado Ejecutivo'),'02');
insert into especialidades values('20',UPPER('Ciberseguridad'),'02');
insert into especialidades values('21',UPPER('Salud Ocupacional'),'02');
insert into especialidades values('22',UPPER('Informática en Soporte'),'02');
insert into especialidades values('23',UPPER('Informática en Redes de Computadoras'),'02');
insert into especialidades values('24',UPPER('Desarrollo Web'),'02');
insert into especialidades values('25',UPPER('Informática en Desarrollo de Software'),'02');
insert into especialidades values('26',UPPER('Informática Empresarial'),'02');
insert into especialidades values('27',UPPER('Executive Service Centers'),'02');
insert into especialidades values('28',UPPER('Ejecutivo para Centros de Servicios'),'02');
insert into especialidades values('29',UPPER('Diseño y Desarrollo Digital'),'02');
insert into especialidades values('30',UPPER('Contabilidad y Finanzas'),'02');
insert into especialidades values('31',UPPER('Contabilidad y Costos'),'02');
insert into especialidades values('32',UPPER('Contabilidad y Auditoría'),'02');
insert into especialidades values('33',UPPER('Contabilidad'),'02');
insert into especialidades values('34',UPPER('Computer Science in Software Development'),'02');
insert into especialidades values('35',UPPER('Computer Networking'),'02');
insert into especialidades values('36',UPPER('Bilingual Secretary'),'02');
insert into especialidades values('37',UPPER('Banca y Finanzas'),'02');
insert into especialidades values('38',UPPER('Administración y Operación Aduanera'),'02');
insert into especialidades values('39',UPPER('Accounting'),'02');
################################ MODALIDAD INDUSTRIAL #################################
insert into especialidades values('40',UPPER('Dibujo y Modelado de Edificaciones'),'03');
insert into especialidades values('41',UPPER('Reparación de los sistemas de vehículos livianos'),'03');
insert into especialidades values('42',UPPER('Productividad y Calidad'),'03');
insert into especialidades values('43',UPPER('Refrigeración y Aire Acondicionado'),'03');
insert into especialidades values('44',UPPER('Mecánica Naval'),'03');
insert into especialidades values('45',UPPER('Mecánica General'),'03');
insert into especialidades values('46',UPPER('Mecánica de Precisión'),'03');
insert into especialidades values('47',UPPER('Mantenimiento Industrial'),'03');
insert into especialidades values('48',UPPER('Electrotecnia'),'03');
insert into especialidades values('49',UPPER('Impresión Offset'),'03');
insert into especialidades values('50',UPPER('Electrónica Industrial'),'03');
insert into especialidades values('51',UPPER('Electrónica en Telecomunicaciones'),'03');
insert into especialidades values('52',UPPER('Electrónica en Mantenimiento de Equipo de Cómputo'),'03');
insert into especialidades values('53',UPPER('Electromecánica'),'03');
insert into especialidades values('54',UPPER('Diseño y Construcción de Muebles y Estructuras'),'03');
insert into especialidades values('55',UPPER('Diseño y Confección de la Moda'),'03');
insert into especialidades values('56',UPPER('Diseño Publicitario'),'03');
insert into especialidades values('57',UPPER('Diseño Gráfico'),'03');
insert into especialidades values('58',UPPER('Dibujo Técnico'),'03');
insert into especialidades values('59',UPPER('Dibujo Arquitectónico'),'03');
insert into especialidades values('60',UPPER('Administración, Logística y Distribución'),'03');
insert into especialidades values('61',UPPER('Logistics Administration and Distribution Program'),'03');
insert into especialidades values('62',UPPER('Information Techology Support'),'03');
insert into especialidades values('63',UPPER('Construcción Civil'),'03');
insert into especialidades values('64',UPPER('Autorremodelado'),'03');

############## ESPECIALIDES BASADAS EN NORMAS POR COMPETENCIAS (PROGRAMA VIEJO)################
insert into especialidades values('999',UPPER('SECRETARIADO EJECUTIVO - Programa BNC'),'02');
insert into especialidades values('998',UPPER('CONTABILIDAD - Programa BNC'),'02');
#####################################################################################################


########################## NIVELES DE ESPECIALIDADES TÉCNICAS ##################################
insert into niveles_tecnicos values('10','DÉCIMO');
insert into niveles_tecnicos values('11','UNDÉCIMO');
insert into niveles_tecnicos values('12','DÚODECIMO');
################################################################################################


################################ SUB-AREAS DE ESPECIALIDADES TÉCNICAS #################################
################################ SECREATARIADO PROGRAMA BNC #################################
insert into sub_areas values('SECR-BNC01','CONVERSATIONAL ENGLISH','999','10');
insert into sub_areas values('SECR-BNC02','CONVERSATIONAL ENGLISH','999','11');
insert into sub_areas values('SECR-BNC03','CONVERSATIONAL ENGLISH','999','12');
insert into sub_areas values('SECR-BNC04','GESTIÓN EMPRESARIAL','999','10');
insert into sub_areas values('SECR-BNC05','GESTIÓN EMPRESARIAL','999','11');
insert into sub_areas values('SECR-BNC06','GESTIÓN EMPRESARIAL','999','12');
insert into sub_areas values('SECR-BNC07','DESTREZAS COMPUTACIONALES ','999','10');
insert into sub_areas values('SECR-BNC08','DESTREZAS COMPUTACIONALES ','999','11');
insert into sub_areas values('SECR-BNC09','DESTREZAS COMPUTACIONALES ','999','12');
insert into sub_areas values('SECR-BNC10','COMUNICACIÓN EMPRESARIAL','999','10');
insert into sub_areas values('SECR-BNC11','COMUNICACIÓN EMPRESARIAL','999','12');
insert into sub_areas values('SECR-BNC12','COMUNICACIÓN EMPRESARIAL Y ADMINISTRACIÓN DE DOCUMENTOS','999','11');
################################ CONTABILIDAD PROGRAMA BNC #################################
insert into sub_areas values('CONT-BNC01',UPPER('Contabilidad'),'998','10');
insert into sub_areas values('CONT-BNC02',UPPER('Contabilidad'),'998','11');
insert into sub_areas values('CONT-BNC03',UPPER('Contabilidad'),'998','12');
insert into sub_areas values('CONT-BNC04',UPPER('Tecnología aplicada a la Contabilidad'),'998','10');
insert into sub_areas values('CONT-BNC05',UPPER('Administración deOrganizaciones Modernas'),'998','10');
insert into sub_areas values('CONT-BNC06',UPPER('Matemática Financiera'),'998','10');
insert into sub_areas values('CONT-BNC07',UPPER('Gestión Empresarial'),'998','11');
insert into sub_areas values('CONT-BNC08',UPPER('Gestión Empresarial'),'998','12');
insert into sub_areas values('CONT-BNC09',UPPER('Normativa Legal Contable '),'998','11');
insert into sub_areas values('CONT-BNC10',UPPER('Contabilidad de Costos'),'998','11');
insert into sub_areas values('CONT-BNC11',UPPER('Principios de Auditoria y Control Interno'),'998','12');
insert into sub_areas values('CONT-BNC12',UPPER('Presupuesto y Estadística '),'998','12');
insert into sub_areas values('CONT-BNC13',UPPER('English for communication'),'998','10');
insert into sub_areas values('CONT-BNC14',UPPER('English for communication'),'998','11');
insert into sub_areas values('CONT-BNC15',UPPER('English for communication'),'998','12');
################################ ADMINISTRACIÓN, LOGISTICA Y DISTRIBUCIÓN - PROGRAMA BNC #################################
insert into sub_areas values('ADM-BNC01',UPPER('Compras'),'60','10');
insert into sub_areas values('ADM-BNC02',UPPER('Importaciones y Exportaciones'),'60','10');
insert into sub_areas values('ADM-BNC03',UPPER('Importaciones y Exportaciones'),'60','12');
insert into sub_areas values('ADM-BNC04',UPPER('Logística '),'60','10');
insert into sub_areas values('ADM-BNC05',UPPER('Logística '),'60','11');
insert into sub_areas values('ADM-BNC06',UPPER('Logística '),'60','12');
insert into sub_areas values('ADM-BNC07',UPPER('Administración de Inventarios'),'60','11');
insert into sub_areas values('ADM-BNC08',UPPER('Operaciones de manufactura'),'60','11');
insert into sub_areas values('ADM-BNC09',UPPER('Operaciones de manufactura'),'60','12');
insert into sub_areas values('ADM-BNC10',UPPER('English for Communication'),'60','10');
insert into sub_areas values('ADM-BNC11',UPPER('PEnglish for Communication'),'60','11');
insert into sub_areas values('ADM-BNC12',UPPER('English for Communication'),'60','12');
################################ CONTABILIDAD #################################
insert into sub_areas values('CONTA-01',UPPER('Gestión contable'),'33','10');
insert into sub_areas values('CONTA-02',UPPER('Gestión contable'),'33','12');
insert into sub_areas values('CONTA-03',UPPER('Gestión en tecnologías digitales contables'),'33','10');
insert into sub_areas values('CONTA-04',UPPER('Gestión tributaria'),'33','11');
insert into sub_areas values('CONTA-05',UPPER('Gestión empresarial para contadores'),'33','11');
insert into sub_areas values('CONTA-06',UPPER('Gestión en costos'),'33','12');
insert into sub_areas values('CONTA-07',UPPER('English Oriented to Accounting'),'33','10');
insert into sub_areas values('CONTA-08',UPPER('English Oriented to Accounting'),'33','11');
insert into sub_areas values('CONTA-09',UPPER('English Oriented to Accounting'),'33','12');
################################ SECRETARIADO #################################
insert into sub_areas values('SECRE-01',UPPER('Comunicación empresarial y servicio al cliente inclusivo'),'19','10');
insert into sub_areas values('SECRE-02',UPPER('Comunicación empresarial y servicio al cliente inclusivo'),'19','11');
insert into sub_areas values('SECRE-03',UPPER('Comunicación empresarial y servicio al cliente inclusivo'),'19','12');
insert into sub_areas values('SECRE-04',UPPER('Destrezas digitales para el procesamiento y archivo de información física-electrónica'),'19','10');
insert into sub_areas values('SECRE-05',UPPER('Destrezas digitales para el procesamiento y archivo de información física-electrónica'),'19','11');
insert into sub_areas values('SECRE-06',UPPER('Destrezas digitales para el procesamiento y archivo de información física-electrónica'),'19','12');
insert into sub_areas values('SECRE-07',UPPER('Gestión corporativa comercial'),'19','10');
insert into sub_areas values('SECRE-08',UPPER('Gestión corporativa comercial'),'19','12');
insert into sub_areas values('SECRE-09',UPPER('Emprendimiento e innovación aplicada al Secretariado Ejecutivo'),'19','11');
insert into sub_areas values('SECRE-10',UPPER('English Oriented to Executive Secretary'),'19','10');
insert into sub_areas values('SECRE-11',UPPER('English Oriented to Executive Secretary'),'19','11');
insert into sub_areas values('SECRE-12',UPPER('English Oriented to Executive Secretary'),'19','12');
################################ DESARROLLO WEB #################################
insert into sub_areas values('DISEWEB-01',UPPER('Tecnologías de la Información (TI)'),'24','10');
insert into sub_areas values('DISEWEB-02',UPPER('Tecnologías de la Información (TI)'),'24','12');
insert into sub_areas values('DISEWEB-03',UPPER('Emprendimiento e innovación'),'24','11');
insert into sub_areas values('DISEWEB-04',UPPER('Programación para web'),'24','10');
insert into sub_areas values('DISEWEB-05',UPPER('Programación para web'),'24','11');
insert into sub_areas values('DISEWEB-06',UPPER('Programación para web'),'24','12');
insert into sub_areas values('DISEWEB-07',UPPER('Diseño de software'),'24','10');
insert into sub_areas values('DISEWEB-08',UPPER('Diseño de software'),'24','11');
insert into sub_areas values('DISEWEB-09',UPPER('Diseño de software'),'24','12');
insert into sub_areas values('DISEWEB-10',UPPER('Soporte TI'),'24','10');
insert into sub_areas values('DISEWEB-11',UPPER('Soporte TI'),'24','11');
insert into sub_areas values('DISEWEB-12',UPPER('Soporte TI'),'24','12');
insert into sub_areas values('DISEWEB-13',UPPER('English Oriented To Web Development'),'24','10');
insert into sub_areas values('DISEWEB-14',UPPER('English Oriented To Web Development'),'24','11');
insert into sub_areas values('DISEWEB-15',UPPER('English Oriented To Web Development'),'24','12');
##########################################################################################################



################################ PERIODOS TÉCNICOS #################################
insert into periodos_tecnicos values('2016','0');
insert into periodos_tecnicos values('2017','0');
insert into periodos_tecnicos values('2018','0');
insert into periodos_tecnicos values('2019','0');
insert into periodos_tecnicos values('2020','0');
insert into periodos_tecnicos values('2021','0');
insert into periodos_tecnicos values('2022','0');
######################################################################################



#########################

#######################################################################################################




CREATE VIEW `vista_usuarios` AS
    SELECT 
        `user_details`.`user_id` AS `user_id`,
        `user_details`.`username` AS `username`,
        `user_details`.`first_name` AS `first_name`,
        `user_details`.`last_name` AS `last_name`,
        `user_details`.`gender` AS `gender`,
        `user_details`.`status` AS `status`
    FROM
        `user_details`